import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
// import { ytDownloader } from "@derimalec/ytdl-to-mp3";
// const youtubeMp3Converter = require('youtube-mp3-converter')

const Home: NextPage = () => {

    const [url, setUrl] = useState<string>('');

    function captureUrl(event: any) {
        setUrl(event.target.value)
    }

    async function convert() {
        // console.log(url);
        // const convertLinkToMp3 = youtubeMp3Converter('../../mp3');

        alert(url);
        // ytDownloader.download(url, '../../mp3');
        // const pathToMp3 = await convertLinkToMp3(url);
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        You <span className="text-[hsl(280,100%,70%)]">P3</span>
                    </h1>
                    <div className="font-bold text-xl text-white">Convert a youtube video to a high-quality MP3.</div>
                    <div className="w-1/2">
                        <div className="mb-6">
                            <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white" />
                            <input type="text" id="default-input" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm 
                            rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 
                            dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white 
                            dark:focus:ring-blue-500 dark:focus:border-blue-500" onChange={captureUrl} value={url} />
                        </div>
                        <button className="text-2x text-white bg-white-100" onClick={() => convert()}>Convert</button>
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
